name: Deploy to WEDOS FTP

on:
  push:
    branches:
      - main  # Pokud se tv치 hlavn칤 v캩tev jmenuje 'master', p콏epi코 to na 'master'

jobs:
  web-deploy:
    name: 游꿀 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 游뚴 Get latest code
      uses: actions/checkout@v4

    - name: 游늭 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        
        # D콡LE콯IT칄 NASTAVEN칈 CESTY:
        # Pokud jsi vytvo콏il FTP u쬴vatele, kter칳 vid칤 JEN slo쬶u 'subdoms/dochazka',
        # nechej server-dir nastaven칳 na './'.
        # Pokud pou쮂셨치코 hlavn칤 칰캜et, napi코 sem cestu: './www/subdoms/dochazka/'
        server-dir: ./
        
        # Co na server NENAHR츼VAT (balast)
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          README.md
          package.json
          package-lock.json
          .gitignore
          .github/**